### PR TITLE
Enable binary output for D compilers

### PR DESCRIPTION
**Pull request by JohanEngelen**
Tested this locally only somewhat. Getting this to work on OS X is a bit of a pain.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Note: this is really for hard-code use only. D compilers output a _lot_ of code, and there is no filtering of all the boilerplate at the moment.

**Comment by JohanEngelen** [comment]
I've fixed the most glaring issues.
I had to introduce another compiler property: `postProcessBinary`, used to post-process the objdump output to get non-C++ demangling working.

**Comment by JohanEngelen** [comment]
Btw, the reason for this PR is because LDC now supports LTO, whose effect you can only see in executable binaries.

**Comment by mattgodbolt** [comment]
Oh cool. I see your other PR is now in merge conflict state; I wasn't sure
if it was ready to be merged yet, given your comments.

I'm going to cherry-pick your changes into the release branch: I'm in the
middle of a big refactor (as you've probably noticed) and I need to do some
further testing before I can move master into release.

**Comment by JohanEngelen** [comment]
I've seen the refactoring :)
For now, at least what doesn't hurt is adding this to `d.defaults.properties`:
```
supportsBinary=true
stubRe=\bmain\b
stubText=int main(){return 0;/*stub provided by Compiler Explorer*/}
binaryHideFuncRe=^(_(?!Dmain).*)$
```

The other stuff I added concerns demangling of D symbols in the binary listing. It's not super important though.

**Comment by mattgodbolt** [comment]
Cool. The main site has been updated with your other changes (minus the
binary stuff).

**Comment by JohanEngelen** [comment]
I've removed all else from the PR. This now just enables the binary output button for the D compilers.

**Comment by mattgodbolt** [comment]
Thanks @JohanEngelen ! I'm working on some acceptance tests to ensure all my changes haven't broken anything, then I'm going to do a push of everything to the live site. Hopefully this week...

**Comment by mattgodbolt** [comment]
So in final testing I've noticed the binary stuff isn't working yet: I run the D compilers under a docker container which is pretty minimal; I'm getting something like:

```/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/gcc-explorer-compiler1161121-130-1fe049i.xvo8figgb9/output.o: relocation R_X86_64_32 against `.rodata.str1.16' can not be used when making a shared object; recompile with -fPIC
/tmp/gcc-explorer-compiler1161121-130-1fe049i.xvo8figgb9/output.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```
I'm guessing this is mainly due to the lack of a "proper" libc in this container. I'll have to work on this, many of the other containers use a "full" libc, but up til now the D language container got away with a much smaller image.

**Comment by JohanEngelen** [comment]
If it helps: to do `-fPIC` with LDC, you have to write `--relocation-model=pic`.

**Comment by mattgodbolt** [comment]
Thanks! I just tried that (no change), but it seems the problem is in the opposite direction. Adding `-static` gives a different result:

```
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libdruntime-ldc.a(runtime.o): In function `_D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv':
/build/src/ldc/runtime/druntime/src/core/runtime.d:(.text._D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv[_D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv]+0x24): undefined reference to `backtrace'
/build/src/ldc/runtime/druntime/src/core/runtime.d:(.text._D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv[_D4core7runtime18runModuleUnitTestsUZ19unittestSegvHandlerUNbiPS4core3sys5posix6signal9siginfo_tPvZv]+0x33): undefined reference to `backtrace_symbols_fd'
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libdruntime-ldc.a(dwarf.o): In function `_D2rt9backtrace5dwarf23traceHandlerOpApplyImplFxAPvMDFKmKxAaZiZi':
/build/src/ldc/runtime/druntime/src/rt/backtrace/dwarf.d:(.text._D2rt9backtrace5dwarf23traceHandlerOpApplyImplFxAPvMDFKmKxAaZiZi[_D2rt9backtrace5dwarf23traceHandlerOpApplyImplFxAPvMDFKmKxAaZiZi]+0x29): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
Compiler exited with result code 1
```

Perhaps there's no `-lrt` or similar in the Alpine linux distribution I'm using. I'll play about a bit more. I'm hoping we can get this working in the upcoming release!

**Comment by mattgodbolt** [comment]
Ah; the workaround I have for `rust` is missing in the `d` container: I use a small build of `glibc` and point rust at it. I'll give that a go.

**Comment by mattgodbolt** [comment]
Ok, back to being bewildered. I pass `-static -L=-L/usr/glibc-compat/lib` (where the glibc now lives) but the error is now:

```
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(curl.o): In function `_D3std3net4curl7CurlAPI7loadAPIFZPv':
/build/src/ldc/runtime/phobos/std/net/curl.d:(.text._D3std3net4curl7CurlAPI7loadAPIFZPv[_D3std3net4curl7CurlAPI7loadAPIFZPv]+0xd): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(path.o): In function `_D3std4path11expandTildeFNbAyaZ18expandFromDatabaseFNbAyaZAya':
/build/src/ldc/runtime/phobos/std/path.d:(.text._D3std4path11expandTildeFNbAyaZ18expandFromDatabaseFNbAyaZAya[_D3std4path11expandTildeFNbAyaZ18expandFromDatabaseFNbAyaZAya]+0x13c): warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket18_sharedStaticCtor1FZv':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket18_sharedStaticCtor1FZv[_D3std6socket18_sharedStaticCtor1FZv]+0x12): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket12InternetHost257__T7getHostVAyaa117_0a2020202020202020202020206175746f2078203d2068746f6e6c28706172616d293b0a2020202020202020202020206175746f206865203d20676574686f73746279616464722826782c20342c206361737428696e74294164647265737346616d696c792e494e4554293b0a2020202020202020TkZ7getHostMFkZb':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket12InternetHost257__T7getHostVAyaa117_0a2020202020202020202020206175746f2078203d2068746f6e6c28706172616d293b0a2020202020202020202020206175746f206865203d20676574686f73746279616464722826782c20342c206361737428696e74294164647265737346616d696c792e494e4554293b0a2020202020202020TkZ7getHostMFkZb[_D3std6socket12InternetHost257__T7getHostVAyaa117_0a2020202020202020202020206175746f2078203d2068746f6e6c28706172616d293b0a2020202020202020202020206175746f206865203d20676574686f73746279616464722826782c20342c206361737428696e74294164647265737346616d696c792e494e4554293b0a2020202020202020TkZ7getHostMFkZb]+0x37): warning: Using 'gethostbyaddr' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(stdio.o): In function `_D3std5stdio11openNetworkFAyatZS3std5stdio4File':
/build/src/ldc/runtime/phobos/std/stdio.d:(.text._D3std5stdio11openNetworkFAyatZS3std5stdio4File[_D3std5stdio11openNetworkFAyatZS3std5stdio4File]+0x42): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket8Protocol17getProtocolByTypeMFNbNeE3std6socket12ProtocolTypeZb':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket8Protocol17getProtocolByTypeMFNbNeE3std6socket12ProtocolTypeZb[_D3std6socket8Protocol17getProtocolByTypeMFNbNeE3std6socket12ProtocolTypeZb]+0x7): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket8Protocol17getProtocolByNameMFNbNexAaZb':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket8Protocol17getProtocolByNameMFNbNexAaZb[_D3std6socket8Protocol17getProtocolByNameMFNbNexAaZb]+0x2c): warning: Using 'getprotobyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket7Service16getServiceByNameMFNbNexAaxAaZb':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket7Service16getServiceByNameMFNbNexAaxAaZb[_D3std6socket7Service16getServiceByNameMFNbNexAaxAaZb]+0x64): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/gcc-explorer/ldc1.0.0/ldc2-1.0.0-linux-x86_64/bin/../lib/libphobos2-ldc.a(socket.o): In function `_D3std6socket7Service16getServiceByPortMFNbNetxAaZb':
/build/src/ldc/runtime/phobos/std/socket.d:(.text._D3std6socket7Service16getServiceByPortMFNbNetxAaZb[_D3std6socket7Service16getServiceByPortMFNbNetxAaZb]+0x30): warning: Using 'getservbyport' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
Compiler exited with result code 0
```

...so now I'm confused. I'm not sure why the initial (apparently PIC by default) code doesn't compile. I'll try it in a non-Alpine container sometime...

**Comment by JohanEngelen** [comment]
This sounds like a serious issue for LDC. So if I understand correctly: the LDC 1.0.0 binary package does not work on Alpine Linux? How about the LDC 1.1.0-beta6 package?

**Comment by mattgodbolt** [comment]
Sadly none of the LDCs want to work in binary mode. I'm certain this is a
problem with Alpine (which uses musl instead of glibc). I will spend some
time moving back to a normal distribution. Sorry for the hold up.

**Comment by JohanEngelen** [comment]
I don't know anything about Alpine or musl, or... well... Do you think this is fixable in LDC? i.e., should I open a bug report about LDC not working (out-of-the-box) on Alpine?

**Comment by mattgodbolt** [comment]
No; I think it's a problem with my setup. gdc has similar (but different)
issues too.

**Comment by mattgodbolt** [comment]
An update on this: I have now moved the images to use full ubuntu containers. I'll test the gdc/ldc binary output and get back to you sometime over the next few days. Thanks again for your patience.

**Comment by mattgodbolt** [comment]
Hi @JohanEngelen -- I've tested and now the binary ldc/gdc works: yay!

However, the static compiled binaries are far too large to disasemble; generating more than 8MB of text. To keep things sane on the public site such giant downloads are truncated. Is there a way to generate a smaller executable?

**Comment by JohanEngelen** [comment]
Great!

:(  the d runtime lib is huge apparently... It's a work-in-progress to reduce reliance on it. :/

Would it help if better filtering is applied such that linked-in functions are discarded?

**Comment by mattgodbolt** [comment]
Yes; that would help. I don't mind a big temporary file if it can be winnowed down to the relevant code easily enough :)

**Pull request merged**
